// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Data;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101000001_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age").HasColumnType("int");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("FullName").IsRequired().HasMaxLength(220).HasColumnType("nvarchar(220)");
                    b.Property<string>("Gender").IsRequired().HasMaxLength(10).HasDefaultValue("").HasColumnType("nvarchar(10)");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("PasswordSalt").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Role").IsRequired().HasMaxLength(20).HasDefaultValue("Patient").HasColumnType("nvarchar(20)");
                    b.Property<string>("Specialization").HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("UserId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");

                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
